datanymizer/datanymizer

.github/workflows/release.yml
CHANGELOG.md
cli/pg_datanymizer/Cargo.toml

Automate release process

---

CHANGELOG.md
README.md
datanymizer_engine/src/engine.rs
datanymizer_engine/src/transformer/mod.rs
datanymizer_engine/src/transformer/uniq_transformer.rs
datanymizer_engine/src/transformer/uniqueness.rs
datanymizer_engine/src/transformers/internet/email.rs
datanymizer_engine/src/transformers/internet/ip.rs
datanymizer_engine/src/transformers/number.rs
datanymizer_engine/src/transformers/phone/transformer.rs
datanymizer_engine/src/uniq_collector.rs

There are some questions in source comments.

UniqTransformer feature

---

CHANGELOG.md
README.md
cli/pg_datanymizer/install.sh

Add installation script

---

README.md

Add seo links

---

.github/workflows/release.yml

Move build process for darwin target to docker image

---

CHANGELOG.md
README.md
datanymizer_engine/docs/new_fk_transformer.md
datanymizer_engine/src/lib.rs
datanymizer_engine/src/locale/mod.rs
datanymizer_engine/src/settings/mod.rs
datanymizer_engine/src/transformer/mod.rs
datanymizer_engine/src/transformers/fk/mod.rs
datanymizer_engine/src/transformers/mod.rs
datanymizer_engine/src/transformers/pipeline.rs
datanymizer_engine/src/transformers/template.rs
datanymizer_engine/tests/new_fk_transformer.rs

Config-wide locale

---

CHANGELOG.md
README.md
datanymizer_dumper/src/lib.rs
datanymizer_dumper/src/postgres/row.rs
datanymizer_dumper/src/postgres/schema_inspector.rs
datanymizer_dumper/src/postgres/table.rs
datanymizer_engine/Cargo.toml
datanymizer_engine/docs/new_fk_transformer.md
datanymizer_engine/src/engine.rs
datanymizer_engine/src/errors.rs
datanymizer_engine/src/lib.rs
datanymizer_engine/src/settings/mod.rs
datanymizer_engine/src/transformer/context.rs
datanymizer_engine/src/transformer/mod.rs
datanymizer_engine/src/transformer/uniq_transformer.rs
datanymizer_engine/src/transformers/capitalize.rs
datanymizer_engine/src/transformers/datetime.rs
datanymizer_engine/src/transformers/fk/mod.rs
datanymizer_engine/src/transformers/internet/email.rs
datanymizer_engine/src/transformers/internet/ip.rs
datanymizer_engine/src/transformers/internet/password.rs
datanymizer_engine/src/transformers/mod.rs
datanymizer_engine/src/transformers/none.rs
datanymizer_engine/src/transformers/number.rs
datanymizer_engine/src/transformers/phone/transformer.rs
datanymizer_engine/src/transformers/pipeline.rs
datanymizer_engine/src/transformers/template.rs
datanymizer_engine/tests/new_fk_transformer.rs

Transformed row context

---

.github/workflows/ci.yml
CHANGELOG.md
datanymizer_engine/src/transformers/capitalize.rs

Also fix the compile error in CI tests.

Fix capitalize

---

CHANGELOG.md
Cargo.lock
README.md
datanymizer_dumper/src/lib.rs
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_dumper/src/postgres/schema_inspector.rs
datanymizer_dumper/src/postgres/table.rs
datanymizer_engine/src/lib.rs
datanymizer_engine/src/locale/mod.rs
datanymizer_engine/src/locale/ru.rs
datanymizer_engine/src/settings/mod.rs
datanymizer_engine/src/settings/table.rs
datanymizer_engine/src/transformers/fk/mod.rs
datanymizer_engine/src/transformers/internet/ip.rs
datanymizer_engine/src/transformers/mod.rs

Dump conditions and limit

---

CHANGELOG.md
README.md
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_dumper/src/postgres/table.rs
datanymizer_engine/src/settings/table.rs

Transform conditions

---

CHANGELOG.md
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_engine/src/transformers/mod.rs
datanymizer_engine/src/transformers/token.rs

HexTokenTransformer

---

CHANGELOG.md
datanymizer_engine/src/transformers/internet/password.rs

Change password params logic

---

CHANGELOG.md
Cargo.lock
README.md
cli/pg_datanymizer/Cargo.toml
datanymizer_dumper/Cargo.toml
datanymizer_engine/Cargo.toml

Preparing for release 0.2.0

---

CHANGELOG.md
datanymizer_dumper/src/postgres/escaper.rs
datanymizer_dumper/src/postgres/mod.rs
datanymizer_dumper/src/postgres/row.rs

Fix PG escaping

---

CHANGELOG.md
Cargo.lock
Dockerfile
cli/pg_datanymizer/Cargo.toml
cli/pg_datanymizer/src/main.rs
datanymizer_dumper/Cargo.toml
datanymizer_dumper/src/lib.rs
datanymizer_dumper/src/postgres/table.rs

SSL support for postgres

---

CHANGELOG.md
Cargo.lock

Security fixes include https://github.com/datanymizer/datanymizer/issues/42

Security updates

---

CHANGELOG.md
datanymizer_engine/src/transformers/internet/email.rs

Fix EmailTransformer

---

CHANGELOG.md
cli/pg_datanymizer/src/app.rs
cli/pg_datanymizer/src/main.rs
cli/pg_datanymizer/src/options.rs
docs/pg_datanymizer.md

Option for allow invalid certs and hosts for SSL

---

CHANGELOG.md
datanymizer_engine/docs/new_fk_transformer.md
datanymizer_engine/src/lib.rs
datanymizer_engine/src/settings/mod.rs
datanymizer_engine/src/transformer/mod.rs
datanymizer_engine/src/transformers/fk/mod.rs
datanymizer_engine/src/transformers/mod.rs
datanymizer_engine/src/transformers/pipeline.rs
datanymizer_engine/src/transformers/template.rs
datanymizer_engine/tests/new_fk_transformer.rs

Replace set_defaults with init

---

CHANGELOG.md
README.md
datanymizer_engine/src/lib.rs
datanymizer_engine/src/store.rs
datanymizer_engine/src/transformer/mod.rs
datanymizer_engine/src/transformers/template/mod.rs
datanymizer_engine/src/transformers/template/store_functions.rs
docs/transformers.md

Key-Value store

---

CHANGELOG.md
cli/pg_datanymizer/src/app.rs
cli/pg_datanymizer/src/options.rs
datanymizer_dumper/src/postgres/dumper.rs
docs/pg_datanymizer.md

Additional pg_dump args

---

CHANGELOG.md
datanymizer_engine/src/transformer/uniq_transformer.rs
datanymizer_engine/src/transformers/internet/email.rs
docs/transformers.md

Email options

---

CHANGELOG.md
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_dumper/src/postgres/mod.rs
datanymizer_dumper/src/postgres/schema_inspector.rs
datanymizer_dumper/src/postgres/sequence.rs
datanymizer_dumper/src/postgres/table.rs

Add sequences

---

.github/workflows/audit.yml

Fresh audit db

---

CHANGELOG.md
Cargo.toml
cli/pg_datanymizer/Cargo.toml

Fix release profile

---

README.md

Add audit badge

---

CHANGELOG.md
datanymizer_engine/src/transformers/template/mod.rs
datanymizer_engine/src/transformers/template/store_functions.rs
docs/transformers.md

https://github.com/datanymizer/datanymizer/discussions/126

Default value for store_read

---

datanymizer_dumper/src/postgres/foreign_key.rs
datanymizer_engine/src/transformer/uniqueness.rs
datanymizer_engine/src/transformers/datetime.rs
datanymizer_engine/src/transformers/internet/password.rs
datanymizer_engine/src/transformers/number.rs
datanymizer_engine/src/transformers/phone/transformer.rs

Fix new Clippy warnings (Rust 1.57)

---

CHANGELOG.md
datanymizer_dumper/tests/postgres/dumper.rs
datanymizer_engine/src/transformers/datetime.rs

Fix datetime formatting issue

---

CHANGELOG.md
Cargo.lock
README.md
datanymizer_dumper/src/lib.rs
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_engine/Cargo.toml
datanymizer_engine/src/settings/filter.rs
docs/config.md

Filter tables with wild cards

---

CHANGELOG.md
datanymizer_dumper/src/lib.rs
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_engine/src/settings/filter.rs
datanymizer_engine/src/settings/mod.rs

Simplify (remove option)

---

CHANGELOG.md
Cargo.lock
datanymizer_engine/Cargo.toml
datanymizer_engine/src/settings/mod.rs

Fix dependabot

---

CHANGELOG.md
Cargo.lock
datanymizer_engine/Cargo.toml
datanymizer_engine/src/transformers/mod.rs
datanymizer_engine/src/transformers/uuid.rs
docs/transformers.md

Guid transformer

---

CHANGELOG.md
Cargo.lock
datanymizer_dumper/src/postgres/dumper.rs
datanymizer_engine/Cargo.toml
datanymizer_engine/src/settings/filter.rs
datanymizer_engine/src/transformers/json/mod.rs
datanymizer_engine/src/transformers/json/selector.rs
datanymizer_engine/src/transformers/mod.rs
datanymizer_engine/src/transformers/template/mod.rs
docs/transformers.md

Json transformer

---

CHANGELOG.md
Cargo.lock
cli/pg_datanymizer/Cargo.toml
cli/pg_datanymizer/src/app.rs
cli/pg_datanymizer/src/main.rs
cli/pg_datanymizer/src/options.rs

Closes https://github.com/datanymizer/datanymizer/security/dependabot/18

Transit from structopt to clap itself

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
SECURITY.md
cli/pg_datanymizer/Cargo.toml
datanymizer_dumper/Cargo.toml
datanymizer_engine/Cargo.toml

Prepare to release 0.7.0
